### ISSUE TITLE
with-ssh fails to parse error

### ISSUE THREAD

**Issue by mothacehe** [artyom-poptsov/guile-ssh#3] opened 2017-04-13 12:42 UTC
Hi,

When calling :
`(with-ssh my-node (use-modules (module-that-doesnt-exist)))`
The guile interpreter returns:
`While compiling expression:`
`ERROR: no code for module (module-that-doesnt-exist)`

In rrepl-get-result from node.scm, only the first line ("While compiling expression") is used to detect the error. I think that's why no error is thrown and the error is silently ignored. The function also returns only 2 values instead of the 4 expected.

Thanks,

Mathieu

**Comment by artyom-poptsov** [comment] 2017-04-14 02:17
Hello Mathieu,

thanks for reporting, it seems like a bug.  I'll look into it in the next few days.

-- Artyom

**Comment by artyom-poptsov** [comment] 2017-04-23 04:21
Hi!

The bug should be fixed in c217d63e3dae2f03e90944d72eae92cb4d089134
Please check if it works for you.

Thanks!

-- Artyom

**Comment by mothacehe** [comment] 2017-04-24 08:10
Hi Artyom,

Thanks for fixing it ! I was able to test the (use-modules (dont-exist)), it works !

I ran into two new use-cases :
`(with-ssh my-node '(+ 2 3 e)`
-> It returns only two values.

`(node-eval my-node '(begin (use-modules (guix)) (open-connection)))`
-> It returns
```
ERROR: In procedure read:
ERROR: In procedure scm_lreadr: #<unknown port>:1:3: Unknown # object: #\<
```
I'm not sure we want with-ssh to parse every possible kind of Guile error, plus every Guile release might break parsing. What do you think ?

Thanks,

Mathieu

**Comment by artyom-poptsov** [comment] 2017-04-24 21:48
Hello Mathieu!

> I ran into two new use-cases :
> (with-ssh my-node '(+ 2 3 e)
> -> It returns only two values.

I tried to reproduce problems you reported.  Here's the program I run:

``` scheme
#!/usr/bin/guile -s
!#

(use-modules (ssh session)
             (ssh auth)
             (ssh dist)
             (srfi srfi-11)) ; for 'let-values'

(let ((s (make-session #:host "localhost")))
  (connect! s)
  (userauth-agent! s)
  (let-values (((a b c d) (with-ssh (make-node s) '(+ 2 3 e))))
    (format #t "a: ~s, b: ~s, c: ~s, d: ~s~%"
            a b c d)))
```

The program prints the following:
```
a: (+ 2 3 e), b: 7, c: "(guile-user)", d: "scheme"
```
Seems like it works OK.  Also please consider that if you want to evaluate some code using `with-ssh` you should pass the code for evaluation to `with-ssh` without the quoting, like this:
``` scheme
(with-ssh my-node (+ 2 3 e))
```
Of course to evaluate this you should ensure that `e` is defined in a remote REPL.

> (node-eval my-node '(begin (use-modules (guix)) (open-connection)))
> -> It returns

According to the [GNU Guix documentation](https://www.gnu.org/software/guix/manual/html_node/The-Store.html), `open-connection` procedure returns a server object as the result.  Objects in Guile usually shown as follows:
```
#<unspecified>
```
I have no fully working GNU Guix installation near me at the moment, but I suppose such a representation of a Guix server object likely contains not all the information that's needed to construct a whole object, therefore it can't be used to construct the object back.  In other words, an object must be serialized on the remote side fist to some kind of readable form so we can read it on our side with Guile-SSH.  And I doubt if it is wise to try to read all the obscure objects used by various Guile programs and modules.  So I think this behaviour is not an error and should be expected.

-- Artyom

**Comment by mothacehe** [comment] 2017-04-25 17:20
Hi Artyom,

I'm really sorry, I made a mistake writing my previous message.
`(with-ssh my-node (+ 2 3 e))`
works and returns 
```
$3 = (+ 2 3 e)
$4 = 3
$5 = "(guile-user)"
$6 = "scheme"
```
as you indicated.

However
`(with-ssh my-node (+ 2 3 e))` where e is not defined,
returns:
```
$1 = "(guile-user)"
$2 = "scheme"
```
when I was expecting either an exception or 4 values.

For the second case, you're right it fails because `#<unspecified>` cannot be constructed. But maybe the raised error should be 'node-repl-error ?

Mathieu

**Comment by artyom-poptsov** [comment] 2017-04-25 17:50
Hello,

> I'm really sorry, I made a mistake writing my previous message.

No problem.  :-)

> However
> `(with-ssh my-node (+ 2 3 e))` where `e` is not defined,
> returns:
> ...
> when I was expecting either an exception or 4 values.

Looks like a bug indeed.

> For the second case, you're right it fails because `#<unspecified>` cannot be constructed. But maybe the raised error should be 'node-repl-error ?

Agreed.  I should take a look at the code and see if I can handle unknown objects better.  

Thanks!

-- Artyom

**Comment by artyom-poptsov** [comment] 2017-04-30 03:40
Hello,

I added handling of "undefined variable" errors.  Now I'm working on handling unknown objects.

-- Artyom

**Comment by mothacehe** [comment] 2017-05-01 10:16
Hi Artyom,

I tested your commit a4f37fb, everything seems fine !

Thanks,

Mathieu

**Comment by artyom-poptsov** [comment] 2017-05-09 07:29
Hello Mathieu,

there's a new Guile-SSH release, [0.11.0](https://github.com/artyom-poptsov/guile-ssh/releases/tag/v0.11.0) -- could you please check if the problems you mentioned are solved?

If everything is OK, I'll close the issue.

Thanks!

-- Artyom

**Closed** 2017-06-18 06:32 UTC
Labels: bug
